contentColumnType: string
fieldGroup: 9c9b7bc0-da32-4a87-8749-d604b14e4fb8
handle: postCategories
instructions: ''
name: 'Post Categories'
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: ''
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: 'group:24ff8f21-eb0d-45ee-a898-f07bc145edfc'
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
