enableVersioning: true
handle: about
name: About
propagationMethod: all
siteSettings:
  61b7b7c1-bad8-4732-8ac6-7c6eb00d0a37:
    enabledByDefault: true
    hasUrls: true
    template: _singles/about
    uriFormat: about
type: single
